import Title from '@/components/title/title';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Wizard",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Wizard layout"></Title>
        </main>
    );
}

export default page