import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';
import React, { Suspense } from 'react';

const BasicAlertCard = React.lazy(() => import('@/components/alert/basic/card'));
const IconDismissAlertCard = React.lazy(() => import('@/components/alert/icon-dismiss/card'));

export const metadata: Metadata = {
    title: "Alert",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Alert"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <BasicAlertCard></BasicAlertCard>
                    </Suspense>
                </div>

                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <IconDismissAlertCard></IconDismissAlertCard>
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
