import React, { Suspense } from 'react';
import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';

const CardBasicNotif = React.lazy(() => import('@/components/notification/basic/card'));

export const metadata: Metadata = {
    title: "Notification",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Notification"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardBasicNotif></CardBasicNotif>
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
