import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import CardSlidercenter from '@/widgets/slider/center/card';
import CardSliderfade from '@/widgets/slider/fade/card';
import CardSliderMultiple from '@/widgets/slider/multiple/card';
import CardSliderSingle from '@/widgets/slider/single/card';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Slider",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Slider"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <CardSliderSingle></CardSliderSingle>
                    <CardSliderMultiple></CardSliderMultiple>
                </div>

                <div className='flex flex-col gap-5'>
                    <CardSlidercenter></CardSlidercenter>
                    <CardSliderfade></CardSliderfade>
                </div>
            </Grid>
        </main>
    );
}

export default page