import React, { Suspense } from 'react';
import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Slider",
    description: "Generated by create next app"
};

const CardSliderSingle = React.lazy(() => import('@/widgets/slider/single/card'));
const CardSliderMultiple = React.lazy(() => import('@/widgets/slider/multiple/card'));
const CardSliderCenter = React.lazy(() => import('@/widgets/slider/center/card'));
const CardSliderFade = React.lazy(() => import('@/widgets/slider/fade/card'));

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Slider"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardSliderSingle />
                    </Suspense>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardSliderMultiple />
                    </Suspense>
                </div>

                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardSliderCenter />
                    </Suspense>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardSliderFade />
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
