import BasicTableCard from '@/components/card/table/basic-table';
import Title from '@/components/title/title';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Regular Table",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="regular table"></Title>

            <div className="grid grid-cols-2 gap-5">
                <div className='flex flex-col gap-5'>
                    <BasicTableCard></BasicTableCard>
                </div>

                <div className='flex flex-col gap-5'>
                </div>
            </div>
        </main>
    );
}

export default page