import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Datepicker",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Datepicker"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                </div>

                <div className='flex flex-col gap-5'>
                </div>
            </Grid>
        </main>
    );
}

export default page