import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { DummyBlog } from '@/dummys/dummy-blog';
import { Blog } from '@/pages/blog/blog';
import { OptionBlog } from '@/pages/blog/option';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Blog",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <div className="flex justify-between items-center">
                <Title name="Blog layout"></Title>
                <OptionBlog
                    addLink=''
                    shareLink=''
                    downloadLink=''>
                </OptionBlog>
            </div>

            <Grid>
                {
                    DummyBlog.map((item, index) => (
                        <Blog
                            key={index}
                            index={index}
                            cover={item.cover}
                            title={item.title}
                            desc={item.desc}
                            categories={item.categories.map(category => category.category)}
                            authors={[{
                                createdBy: item.author.createdBy,
                                photoProfile: item.author.photoProfile,
                                createdAt: item.author.createdAt
                            }]}
                            totalComments={item.totalComments}
                            totalLikes={item.totalLikes}
                            totalViews={item.totalViews}>
                        </Blog>
                    ))
                }
            </Grid>
        </main>
    );
}

export default page