import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import CardImageZoom from '@/widgets/image-zoom/card';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Image Zoom",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Image Zoom"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <CardImageZoom></CardImageZoom>
                </div>
            </Grid>
        </main>
    );
}

export default page