import React, { Suspense } from 'react';
import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Image Zoom",
    description: "Generated by create next app"
};

const CardImageZoom = React.lazy(() => import('@/widgets/image-zoom/card'));

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Image Zoom"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardImageZoom />
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
