import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Regular Table   ",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <div>
            <h1>test</h1>
        </div>
    );
}

export default page