import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Regular Table",
    description: "Generated by create next app"
};

export const titlePage = "table";

const page = () => {
    return (
        <div>
            testing
        </div>
    );
}

export default page