export const DummyBlog = [
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Lorem Ipsum Dolor Sit Amet",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et venenatis velit, sit amet malesuada erat. Nullam at interdum nulla.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "John Doe",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-03-09",
        },
        totalComments: 10,
        totalViews: 500,
        totalLikes: 30,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Varius Diam",
        desc: "Pellentesque varius diam vitae lectus fermentum, quis varius ante pretium. Fusce ultrices libero ac odio luctus, id rutrum justo sodales.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Jane Smith",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-03-08",
        },
        totalComments: 5,
        totalViews: 300,
        totalLikes: 20,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Mattis Neque Eget",
        desc: "Vestibulum mattis neque eget justo commodo, vel congue dolor elementum. Nullam et orci nec augue luctus interdum nec vitae sapien.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Alice Johnson",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-03-06",
        },
        totalComments: 8,
        totalViews: 450,
        totalLikes: 25,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Duis Tristique Nibh Non Sapien",
        desc: "Duis tristique nibh non sapien congue, ut rutrum lectus elementum. Vivamus vestibulum, odio ac commodo posuere, ligula turpis egestas.",
        categories: [
            { category: "Food" },
            { category: "Cooking" },
        ],
        author: {
            createdBy: "Michael Brown",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-03-05",
        },
        totalComments: 15,
        totalViews: 600,
        totalLikes: 40,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nulla Pharetra Orci In Felis",
        desc: "Nulla pharetra orci in felis vestibulum, at malesuada ligula eleifend. Proin sit amet nisi id elit bibendum ultrices in sed lectus.",
        categories: [
            { category: "Fashion" },
            { category: "Style" },
        ],
        author: {
            createdBy: "Emily Wilson",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-03-04",
        },
        totalComments: 12,
        totalViews: 700,
        totalLikes: 35,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Suspendisse Eu Turpis In Eros",
        desc: "Suspendisse eu turpis in eros elementum convallis. Nullam in ex nec purus congue tincidunt. Phasellus porttitor tortor ut arcu commodo.",
        categories: [
            { category: "Art" },
            { category: "Design" },
        ],
        author: {
            createdBy: "David Clark",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-03-03",
        },
        totalComments: 20,
        totalViews: 800,
        totalLikes: 50,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Fusce Feugiat Eget Ligula Sed",
        desc: "Fusce feugiat eget ligula sed consequat. Ut sed felis quis ex finibus vestibulum eget ut mauris. Vestibulum cursus tincidunt sem.",
        categories: [
            { category: "Education" },
            { category: "Learning" },
        ],
        author: {
            createdBy: "Sophia Evans",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-03-02",
        },
        totalComments: 18,
        totalViews: 900,
        totalLikes: 45,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Aenean Sit Amet Lacus Purus",
        desc: "Aenean sit amet lacus purus. Morbi feugiat arcu a libero venenatis auctor. Nam condimentum quam vel consectetur tincidunt.",
        categories: [
            { category: "Science" },
            { category: "Research" },
        ],
        author: {
            createdBy: "Ethan Garcia",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-03-01",
        },
        totalComments: 25,
        totalViews: 1000,
        totalLikes: 60,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title:

 "Curabitur Eleifend Odio Sit Amet",
        desc: "Curabitur eleifend odio sit amet libero accumsan, et posuere nulla ultricies. Phasellus et nisi sed justo vehicula vehicula vitae sit amet.",
        categories: [
            { category: "Books" },
            { category: "Literature" },
        ],
        author: {
            createdBy: "Olivia Martin",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-02-29",
        },
        totalComments: 30,
        totalViews: 1100,
        totalLikes: 70,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque A Diam Nec Justo",
        desc: "Pellentesque a diam nec justo tincidunt vehicula. Vestibulum ut tincidunt justo. Vestibulum consectetur nulla at justo pharetra viverra.",
        categories: [
            { category: "Gaming" },
            { category: "Entertainment" },
        ],
        author: {
            createdBy: "Daniel Walker",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-02-28",
        },
        totalComments: 28,
        totalViews: 1200,
        totalLikes: 65,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Ante Ipsum Primis",
        desc: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi vitae elit eget eros egestas bibendum.",
        categories: [
            { category: "Music" },
            { category: "Concerts" },
        ],
        author: {
            createdBy: "Emma Wright",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-02-27",
        },
        totalComments: 22,
        totalViews: 1300,
        totalLikes: 55,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Aliquam Non Elit Et Purus",
        desc: "Aliquam non elit et purus suscipit sollicitudin. Nulla lobortis massa et ex rutrum, at lacinia lorem fringilla. Phasellus at luctus lorem.",
        categories: [
            { category: "Politics" },
            { category: "Government" },
        ],
        author: {
            createdBy: "Mason Taylor",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-02-26",
        },
        totalComments: 35,
        totalViews: 1400,
        totalLikes: 75,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Donec Tristique Mollis Eros",
        desc: "Donec tristique mollis eros, at congue felis aliquet ut. In eget odio sit amet nisi venenatis venenatis in eu quam.",
        categories: [
            { category: "Nature" },
            { category: "Environment" },
        ],
        author: {
            createdBy: "Ella Harris",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-02-25",
        },
        totalComments: 40,
        totalViews: 1500,
        totalLikes: 80,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Ut Enim Quis Justo",
        desc: "Vivamus ut enim quis justo lobortis dictum. Nullam sit amet diam ac urna eleifend fringilla nec nec magna.",
        categories: [
            { category: "Business" },
            { category: "Finance" },
        ],
        author: {
            createdBy: "William King",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-02-24",
        },
        totalComments: 32,
        totalViews: 1600,
        totalLikes: 70,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Fusce Ullamcorper Hendrerit Orci",
        desc: "Fusce ullamcorper hendrerit orci, at porttitor lectus mattis et. Proin vestibulum tincidunt purus, et fermentum velit blandit non.",
        categories: [
            { category: "Sports" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Sophie Cooper",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-02-23",
        },
        totalComments: 25,
        totalViews: 1700,
        totalLikes:

 75,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Morbi Sagittis Luctus Eros",
        desc: "Morbi sagittis luctus eros, eu malesuada urna tempus ac. Phasellus tristique erat in tortor ultrices, non pharetra dolor volutpat.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "Lucas White",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-02-22",
        },
        totalComments: 18,
        totalViews: 1800,
        totalLikes: 80,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Aenean Auctor Tristique Massa",
        desc: "Aenean auctor tristique massa, vel consequat risus convallis sed. Nullam posuere ex nec ante eleifend, a ullamcorper justo iaculis.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Sophia Turner",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-02-21",
        },
        totalComments: 20,
        totalViews: 1900,
        totalLikes: 85,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nullam Tincidunt Nisl In Neque",
        desc: "Nullam tincidunt nisl in neque venenatis, id fermentum purus facilisis. In vitae semper lectus. Curabitur rutrum elit sed varius placerat.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Liam Harris",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-02-20",
        },
        totalComments: 15,
        totalViews: 2000,
        totalLikes: 90,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Odio Massa Convallis",
        desc: "Vestibulum odio massa, convallis nec lectus in, cursus ullamcorper magna. Proin aliquet odio ac lacus interdum tempus.",
        categories: [
            { category: "Food" },
            { category: "Cooking" },
        ],
        author: {
            createdBy: "Sophia Baker",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-02-19",
        },
        totalComments: 25,
        totalViews: 2100,
        totalLikes: 95,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Etiam Feugiat Orci In Lobortis",
        desc: "Etiam feugiat orci in lobortis ullamcorper. Fusce in libero a justo ullamcorper sollicitudin at vel purus.",
        categories: [
            { category: "Fashion" },
            { category: "Style" },
        ],
        author: {
            createdBy: "Noah Phillips",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-02-18",
        },
        totalComments: 30,
        totalViews: 2200,
        totalLikes: 100,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Cras Quis Feugiat Eros Pharetra",
        desc: "Cras quis feugiat eros, pharetra cursus lacus. Vivamus sed nunc vitae nisl eleifend placerat at a nulla.",
        categories: [
            { category: "Art" },
            { category: "Design" },
        ],
        author: {
            createdBy: "Ava Young",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-02-17",
        },
        totalComments: 35,
        totalViews: 2300,
        totalLikes: 105,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Mauris In Mi Eu Felis Efficitur",
        desc: "Mauris in mi eu felis efficitur semper. Fusce sed interdum orci. Nulla facilisi. Donec at lobortis odio, in malesuada eros.",
        categories: [
            { category: "Education" },
            { category: "Learning" },
        ],
        author: {
            createdBy: "James Turner",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-02-16",
        },
        totalComments: 40,
        totalViews: 2400,
        totalLikes: 110,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Posuere Consectetur",
        desc: "Pellentesque posuere consectetur purus sit amet sollicitudin. In imperdiet eros a velit pretium lacinia.",
        categories: [
            { category: "Science" },
            { category: "Research" },
        ],
        author: {
            createdBy: "Isabella Wilson",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-02-15",
        },
        totalComments: 45,
        totalViews: 2500,
        totalLikes: 115,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Curabitur Eu Metus Fringilla",
        desc: "Curabitur eu metus fringilla, posuere nisl eget, convallis odio. Nullam egestas, justo ac tincidunt hendrerit, lorem orci tempor quam.",
        categories: [
            { category: "Books" },
            { category: "Literature" },
        ],
        author: {
            createdBy: "Ethan Lee",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-02-14",
        },
        totalComments: 50,
        totalViews: 2600,
        totalLikes: 120,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Euismod Mollis Nibh",
        desc: "Vestibulum euismod mollis nibh, sed facilisis ex fermentum eu. Etiam auctor, augue vel fermentum tristique, sem eros finibus enim.",
        categories: [
            { category: "Gaming" },
            { category: "Entertainment" },
        ],
        author: {
            createdBy: "Mia Turner",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-02-13",
        },
        totalComments: 55,
        totalViews: 2700,
        totalLikes: 125,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Aliquam Ultricies Tempus Justo",
        desc: "Aliquam ultricies tempus justo, nec euismod purus tincidunt et. In venenatis nibh eu vehicula consectetur.",
        categories: [
            { category: "Music" },
            { category: "Concerts" },
        ],
        author: {
            createdBy: "Oliver Brown",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-02-12",
        },
        totalComments: 60,
        totalViews: 2800,
        totalLikes: 130,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Integer Nisl Tellus Tempus",
        desc: "Integer nisl tellus, tempus eu mi ut, varius volutpat ligula. Nulla consequat felis id turpis tincidunt, ut luctus velit eleifend.",
        categories: [
            { category: "Politics" },
            { category: "Government" },
        ],
        author: {
            createdBy: "Sophie Walker",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-02-11",
        },
        totalComments: 65,
        totalViews: 2900,
        totalLikes: 135,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Et Metus Sit Amet",
        desc: "Vivamus et metus sit amet tortor accumsan dictum. Integer a urna ut felis volutpat sodales. Morbi in augue nec turpis molestie.",
        categories: [
            { category: "Nature" },
            { category: "Environment" },
        ],
        author: {
            createdBy: "Lucas Martinez",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-02-10",
        },
        totalComments: 70,
        totalViews: 3000,
        totalLikes: 140,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Mauris Eleifend Lectus Vel Est",
        desc: "Mauris eleifend lectus vel est tincidunt, sit amet vestibulum felis rhoncus. Proin consequat fermentum vestibulum.",
        categories: [
            { category: "Business" },
            { category: "Finance" },
        ],
        author: {
            createdBy: "Ava Clark",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-02-09",
        },
        totalComments: 75,
        totalViews: 3100,
        totalLikes: 145,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Phasellus Dui Purus Eget Elit",
        desc: "Phasellus dui purus, eget elit accumsan, faucibus vehicula odio. Sed feugiat mi eu vehicula maximus. Mauris malesuada, libero et mollis.",
        categories: [
            { category: "Sports" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "William White",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-02-08",
        },
        totalComments: 80,
        totalViews: 3200,
        totalLikes: 150,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Non Semper Neque",
        desc: "Vestibulum non semper neque. Quisque id eros ultricies, bibendum quam et, aliquet ipsum. Etiam consectetur orci ac vehicula lacinia.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "Emma Martinez",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-02-07",
        },
        totalComments: 85,
        totalViews: 3300,
        totalLikes: 155,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Fusce Velit Dui Tristique Elit",
        desc: "Fusce velit dui, tristique elit pretium, facilisis risus. Integer commodo metus vel turpis eleifend, sed laoreet velit sodales.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Lucas Turner",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-02-06",
        },
        totalComments: 90,
        totalViews: 3400,
        totalLikes: 160,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Sed Tempus Turpis Non Purus",
        desc: "Sed tempus turpis non purus vehicula facilisis. Nulla eget quam in nulla viverra faucibus. In volutpat urna id sapien dignissim.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Sophia King",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-02-05",
        },
        totalComments: 95,
        totalViews: 3500,
        totalLikes: 165,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Integer Auctor Felis In Augue",
        desc: "Integer auctor felis in augue feugiat, et pharetra velit suscipit. Suspendisse potenti. Nam eget risus sit amet ante facilisis lacinia.",
        categories: [
            { category: "Food" },
            { category: "Cooking" },
        ],
        author: {
            createdBy: "Olivia Clark",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-02-04",
        },
        totalComments: 100,
        totalViews: 3600,
        totalLikes: 170,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Eu Augue Eget Odio",
        desc: "Vestibulum eu augue eget odio malesuada fermentum eget nec mi. Sed nec mauris auctor, ultricies justo eget, venenatis nulla.",
        categories: [
            { category: "Fashion" },
            { category: "Style" },
        ],
        author: {
            createdBy: "Isaac Martinez",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-02-03",
        },
        totalComments: 105,
        totalViews: 3700,
        totalLikes: 175,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Duis Suscipit Sapien A Eros",
        desc: "Duis suscipit sapien a eros tincidunt, id egestas magna varius. Maecenas quis velit eget lorem convallis ultricies eget eget felis.",
        categories: [
            { category: "Art" },
            { category: "Design" },
        ],
        author: {
            createdBy: "Amelia Lee",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-02-02",
        },
        totalComments: 110,
        totalViews: 3800,
        totalLikes: 180,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Praesent Consectetur Magna",
        desc: "Praesent consectetur magna ac libero facilisis, in tincidunt nulla euismod. Curabitur feugiat eros non quam bibendum consectetur.",
        categories: [
            { category: "Education" },
            { category: "Learning" },
        ],
        author: {
            createdBy: "Elijah Clark",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-02-01",
        },
        totalComments: 115,
        totalViews: 3900,
        totalLikes: 185,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nulla Egestas Elit In Diam",
        desc: "Nulla egestas elit in diam fermentum luctus. In nec quam quis mi placerat dignissim. Ut lacinia lorem nec libero posuere cursus.",
        categories: [
            { category: "Science" },
            { category: "Research" },
        ],
        author: {
            createdBy: "Mia Baker",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-01-31",
        },
        totalComments: 120,
        totalViews: 4000,
        totalLikes: 190,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Mauris Et Risus Eleifend",
        desc: "Mauris et risus eleifend, condimentum ex vel, ullamcorper odio. Fusce at ex id ligula egestas laoreet. Etiam eleifend justo vel eros.",
        categories: [
            { category: "Books" },
            { category: "Literature" },
        ],
        author: {
            createdBy: "Oliver Clark",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-01-30",
        },
        totalComments: 125,
        totalViews: 4100,
        totalLikes: 195,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Ultricies Ipsum",
        desc: "Vestibulum ultricies ipsum a velit hendrerit, eget condimentum leo consectetur. Nulla id elit in leo eleifend elementum sit amet ut velit.",
        categories: [
            { category: "Gaming" },
            { category: "Entertainment" },
        ],
        author: {
            createdBy: "Sophia Young",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-01-29",
        },
        totalComments: 130,
        totalViews: 4200,
        totalLikes: 200

,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Aliquam Consequat Tincidunt",
        desc: "Aliquam consequat tincidunt mi, ac aliquet ex consectetur sed. Suspendisse potenti. Maecenas consectetur eros vel velit suscipit tincidunt.",
        categories: [
            { category: "Music" },
            { category: "Concerts" },
        ],
        author: {
            createdBy: "Noah Brown",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-01-28",
        },
        totalComments: 135,
        totalViews: 4300,
        totalLikes: 205,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Cras Aliquam Dolor Sed Eros",
        desc: "Cras aliquam dolor sed eros dapibus, id elementum dui semper. Pellentesque tincidunt lacus in sapien luctus, vitae accumsan turpis dictum.",
        categories: [
            { category: "Politics" },
            { category: "Government" },
        ],
        author: {
            createdBy: "Mason King",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-01-27",
        },
        totalComments: 140,
        totalViews: 4400,
        totalLikes: 210,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Donec Volutpat Lacus At Magna",
        desc: "Donec volutpat lacus at magna dignissim, a commodo sem varius. Fusce pharetra eleifend lectus ut dignissim.",
        categories: [
            { category: "Nature" },
            { category: "Environment" },
        ],
        author: {
            createdBy: "Ella White",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-01-26",
        },
        totalComments: 145,
        totalViews: 4500,
        totalLikes: 215,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Suspendisse Facilisis Nunc",
        desc: "Suspendisse facilisis nunc eget nunc luctus, a aliquet magna volutpat. Duis luctus arcu vitae ante volutpat, at hendrerit ligula posuere.",
        categories: [
            { category: "Business" },
            { category: "Finance" },
        ],
        author: {
            createdBy: "Sophie Martinez",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-01-25",
        },
        totalComments: 150,
        totalViews: 4600,
        totalLikes: 220,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Tincidunt Gravida Ligula",
        desc: "Vivamus tincidunt gravida ligula, in ultricies elit sagittis a. Sed efficitur commodo metus, vel facilisis libero fermentum id.",
        categories: [
            { category: "Sports" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "William Turner",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-01-24",
        },
        totalComments: 155,
        totalViews: 4700,
        totalLikes: 225,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Porttitor Euismod",
        desc: "Pellentesque porttitor euismod libero, vitae consequat justo. Proin nec tortor ac neque placerat suscipit et eget lorem.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "Emma Young",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-01-23",
        },
        totalComments: 160,
        totalViews: 4800,
        totalLikes: 230,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Fusce Dignissim Nisl Non",
        desc: "Fusce dignissim nisl non purus lacinia consequat. Proin non orci sed mauris euismod ultricies. Nullam nec odio vitae libero malesuada.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Lucas King",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-01-22",
        },
        totalComments: 165,
        totalViews: 4900,
        totalLikes: 235,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Sed Aliquam Lectus Ut",
        desc: "Sed aliquam lectus ut ante suscipit tempor. Nam fermentum tincidunt nunc sit amet tincidunt. Curabitur in velit enim.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Sophia Clark",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-01-21",
        },
        totalComments: 170,
        totalViews: 5000,
        totalLikes: 240,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Phasellus In Metus Velit",
        desc: "Phasellus in metus velit. Sed sed justo non erat efficitur consectetur id eu elit. Suspendisse potenti. Nunc eget urna est.",
        categories: [
            { category: "Food" },
            { category: "Cooking" },
        ],
        author: {
            createdBy: "Olivia Martinez",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-01-20",
        },
        totalComments: 175,
        totalViews: 5100,
        totalLikes: 245,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Elementum Massa",
        desc: "Vivamus elementum massa et sem convallis, vel consectetur nisi facilisis. Nulla efficitur posuere nisl, id convallis nunc malesuada ac.",
        categories: [
            { category: "Fashion" },
            { category: "Style" },
        ],
        author: {
            createdBy: "Isaac Turner",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-01-19",
        },
        totalComments: 180

,
        totalViews: 5200,
        totalLikes: 250,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Maecenas Varius Risus Sit",
        desc: "Maecenas varius risus sit amet eros dignissim, eget iaculis ligula fringilla. Integer at sapien a quam dapibus placerat non ac neque.",
        categories: [
            { category: "Art" },
            { category: "Design" },
        ],
        author: {
            createdBy: "Amelia Harris",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-01-18",
        },
        totalComments: 185,
        totalViews: 5300,
        totalLikes: 255,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nullam Id Eros Bibendum",
        desc: "Nullam id eros bibendum, pellentesque orci ac, lobortis urna. Aenean ultrices tincidunt ipsum, ac fermentum libero vulputate non.",
        categories: [
            { category: "Education" },
            { category: "Learning" },
        ],
        author: {
            createdBy: "Elijah Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-01-17",
        },
        totalComments: 190,
        totalViews: 5400,
        totalLikes: 260,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Praesent Eleifend Sit Amet",
        desc: "Praesent eleifend sit amet arcu vel pharetra. Morbi vitae mi in dui pulvinar consequat ut nec ante. Fusce gravida, risus eget lacinia.",
        categories: [
            { category: "Science" },
            { category: "Research" },
        ],
        author: {
            createdBy: "Mia Walker",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-01-16",
        },
        totalComments: 195,
        totalViews: 5500,
        totalLikes: 265,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Curabitur Vulputate Tincidunt",
        desc: "Curabitur vulputate tincidunt elit, eu convallis dolor commodo in. Vivamus vel fringilla ligula. Quisque faucibus mi quis metus scelerisque.",
        categories: [
            { category: "Books" },
            { category: "Literature" },
        ],
        author: {
            createdBy: "Oliver Phillips",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-01-15",
        },
        totalComments: 200,
        totalViews: 5600,
        totalLikes: 270,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Etiam Aliquam Arcu Auctor",
        desc: "Etiam aliquam arcu auctor ligula imperdiet, a interdum nulla fringilla. In in ante convallis, dapibus purus vel, commodo lorem.",
        categories: [
            { category: "Gaming" },
            { category: "Entertainment" },
        ],
        author: {
            createdBy: "Sophia Clark",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-01-14",
        },
        totalComments: 205,
        totalViews: 5700,
        totalLikes: 275,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque A Sapien Eget",
        desc: "Pellentesque a sapien eget felis convallis tincidunt. Fusce nec dolor et lorem rutrum dapibus eget a mi.",
        categories: [
            { category: "Music" },
            { category: "Concerts" },
        ],
        author: {
            createdBy: "Noah Young",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-01-13",
        },
        totalComments: 210,
        totalViews: 5800,
        totalLikes: 280,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Tempus Tempor",
        desc: "Vestibulum tempus tempor efficitur. Phasellus congue sem eu tortor dignissim ultricies. Fusce maximus accumsan luctus.",
        categories: [
            { category: "Politics" },
            { category: "Government" },
        ],
        author: {
            createdBy: "Mason Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-01-12",
        },
        totalComments: 215,
        totalViews: 5900,
        totalLikes: 285,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Donec Fermentum Egestas",
        desc: "Donec fermentum egestas metus, nec fringilla risus venenatis vel. Phasellus vel justo condimentum, interdum nisi vel, facilisis erat.",
        categories: [
            { category: "Nature" },
            { category: "Environment" },
        ],
        author: {
            createdBy: "Ella Walker",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-01-11",
        },
        totalComments: 220,
        totalViews: 6000,
        totalLikes: 290,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Etiam Venenatis Ligula Sit",
        desc: "Etiam venenatis ligula sit amet justo luctus, sit amet ullamcorper nunc fermentum. Vivamus eget ante a felis auctor pharetra.",
        categories: [
            { category: "Business" },
            { category: "Finance" },
        ],
        author: {
            createdBy: "Sophie Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-01-10",
        },
        totalComments: 225,
        totalViews: 6100,
        totalLikes: 295,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Mauris Posuere Tortor",
        desc: "Mauris posuere tortor vitae nunc lobortis ultricies. Integer lacinia eros id ultricies suscipit. Quisque ultrices risus nec nulla vestibulum.",
        categories: [
            { category: "Sports" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "William Clark",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-01-09",
        },
        totalComments: 230,
        totalViews: 6200,
        totalLikes: 300,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Sed Eget Dui Auctor",
        desc: "Sed eget dui auctor, fermentum ligula id, pellentesque urna. In vehicula, urna vel faucibus pellentesque, justo eros maximus ante.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "Emma Martinez",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-01-08",
        },
        totalComments: 235,
        totalViews: 6300,
        totalLikes: 305,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Habitant Morbi",
        desc: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam id est quis nulla feugiat mattis.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Lucas Young",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-01-07",
        },
        totalComments: 240,
        totalViews: 6400,
        totalLikes: 310,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Mollis Turpis",
        desc: "Vivamus mollis turpis vel pretium vulputate. Proin vehicula accumsan lectus a cursus. Donec ut quam eu nulla tincidunt fermentum.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Sophia Martinez",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-01-06",
        },
        totalComments: 245,
        totalViews: 6500,
        totalLikes: 315,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Suspendisse Potenti Ut Dui",
        desc: "Suspendisse potenti. Ut dui neque, iaculis in augue ac, lobortis consequat eros. Vivamus luctus, mi et sollicitudin lobortis.",
        categories: [
            { category: "Food" },
            { category: "Cooking" },
        ],
        author: {
            createdBy: "Olivia Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2024-01-05",
        },
        totalComments: 250,
        totalViews: 6600,
        totalLikes: 320,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nullam Auctor Felis Non",
        desc: "Nullam auctor felis non neque convallis vestibulum. Integer vitae neque in eros tincidunt bibendum. Sed eu augue a diam feugiat commodo.",
        categories: [
            { category: "Fashion" },
            { category: "Style" },
        ],
        author: {
            createdBy: "Isaac Phillips",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2024-01-04",
        },
        totalComments: 255,
        totalViews: 6700,
        totalLikes: 325,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Duis Eu Lacinia Mi",
        desc: "Duis eu lacinia mi, nec luctus tortor. Nulla ultrices tellus vitae tempus sodales. Phasellus eleifend justo id velit condimentum placerat.",
        categories: [
            { category: "Art" },
            { category: "Design" },
        ],
        author: {
            createdBy: "Amelia Walker",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2024-01-03",
        },
        totalComments: 260,
        totalViews: 6800,
        totalLikes: 330,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Praesent Malesuada Ligula",
        desc: "Praesent malesuada ligula in metus tempus, quis efficitur tortor volutpat. Sed sit amet pharetra est. Nam tristique lacinia vestibulum.",
        categories: [
            { category: "Education" },
            { category: "Learning" },
        ],
        author: {
            createdBy: "Elijah Clark",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2024-01-02",
        },
        totalComments: 265,
        totalViews: 6900,
        totalLikes: 335,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Mauris Non Molestie Arcu",
        desc: "Mauris non molestie arcu. Duis tempor leo vel tempus dapibus. Sed sed libero at lacus congue molestie id non erat.",
        categories: [
            { category: "Science" },
            { category: "Research" },
        ],
        author: {
            createdBy: "Mia Phillips",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2024-01-01",
        },
        totalComments: 270,
        totalViews: 7000,
        totalLikes: 340,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Curabitur Eget Eros Egestas",
        desc: "Curabitur eget eros egestas, tristique felis et, mattis ipsum. Vestibulum nec eros vitae arcu tincidunt vulputate.",
        categories: [
            { category: "Books" },
            { category: "Literature" },
        ],
        author: {
            createdBy: "Oliver Clark",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-12-31",
        },
        totalComments: 275,
        totalViews: 7100,
        totalLikes: 345,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Nisl In Lobortis",
        desc: "Vestibulum nisl in lobortis consequat. In tristique vel mi vitae pellentesque. Cras et tellus a augue tincidunt pretium.",
        categories: [
            { category: "Gaming" },
            { category: "Entertainment" },
        ],
        author: {
            createdBy: "Sophia Walker",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-12-30",
        },
        totalComments: 280,
        totalViews: 7200,
        totalLikes: 350,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Aliquam Rutrum Lacus Eu",
        desc: "Aliquam rutrum lacus eu nulla placerat, in scelerisque eros egestas. Nam finibus, nulla eget malesuada luctus, turpis nisi ullamcorper.",
        categories: [
            { category: "Music" },
            { category: "Concerts" },
        ],
        author: {
            createdBy: "Noah Clark",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-12-29",
        },
        totalComments: 285,
        totalViews: 7300,
        totalLikes: 355,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Cras Sagittis Diam At",
        desc: "Cras sagittis diam at lectus fringilla, a tincidunt dui consequat. Phasellus interdum libero id tellus mattis, eget lacinia turpis.",
        categories: [
            { category: "Politics" },
            { category: "Government" },
        ],
        author: {
            createdBy: "Mason Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-12-28",
        },
        totalComments: 290,
        totalViews: 7400,
        totalLikes: 360,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Donec At Tellus Eleifend",
        desc: "Donec at tellus eleifend, eleifend lectus in, tincidunt velit. Vestibulum tempor urna ut fermentum consectetur.",
        categories: [
            { category: "Nature" },
            { category: "Environment" },
        ],
        author: {
            createdBy: "Ella Walker",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-12-27",
        },
        totalComments: 295,
        totalViews: 7500,
        totalLikes: 365,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nulla Tincidunt Eget Elit",
        desc: "Nulla tincidunt eget elit nec varius. Cras efficitur semper turpis, at consectetur odio malesuada non. Mauris vitae velit id libero.",
        categories: [
            { category: "Business" },
            { category: "Finance" },
        ],
        author: {
            createdBy: "Sophie Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-12-26",
        },
        totalComments: 300,
        totalViews: 7600,
        totalLikes: 370,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Auctor Erat Ut",
        desc: "Vivamus auctor erat ut ultrices suscipit. Duis eleifend bibendum lacus, eu fermentum nunc bibendum sit amet. Nullam gravida, purus sit amet.",
        categories: [
            { category: "Sports" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "William Clark",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-12-25",
        },
        totalComments: 305,
        totalViews: 7700,
        totalLikes: 375,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Quis Augue Eu",
        desc: "Pellentesque quis augue eu mauris efficitur vestibulum. Vestibulum fermentum nunc vitae enim malesuada, sed malesuada nisi pharetra.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "Emma Walker",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-12-24",
        },
        totalComments: 310,
        totalViews: 7800,
        totalLikes: 380,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Fusce Dui Tortor",
        desc: "Fusce dui tortor, tincidunt ac malesuada non, varius vel purus. Aliquam erat volutpat. Cras vel fringilla est.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Lucas Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-12-23",
        },
        totalComments: 315,
        totalViews: 7900,
        totalLikes: 385,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Sed Euismod Massa At",
        desc: "Sed euismod massa at tortor sagittis, id sagittis diam pulvinar. Nulla facilisi. Suspendisse potenti. Ut accumsan vehicula mi.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Sophia Clark",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-12-22",
        },
        totalComments: 320,
        totalViews: 8000,
        totalLikes: 390,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Phasellus In Metus In",
        desc: "Phasellus in metus in purus tristique ullamcorper vitae id odio. Morbi dignissim, justo et ultricies bibendum, ex lacus varius dolor.",
        categories: [
            { category: "Food" },
            { category: "Cooking" },
        ],
        author: {
            createdBy: "Olivia Martinez",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-12-21",
        },
        totalComments: 325,
        totalViews: 8100,
        totalLikes: 395,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Et Eros Sapien",
        desc: "Vivamus et eros sapien. Curabitur efficitur nibh id ipsum accumsan imperdiet. Cras non eros ullamcorper, malesuada elit sed, lacinia neque.",
        categories: [
            { category: "Fashion" },
            { category: "Style" },
        ],
        author: {
            createdBy: "Isaac Turner",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-12-20",
        },
        totalComments: 330,
        totalViews: 8200,
        totalLikes: 400,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Maecenas Feugiat Augue Ut",
        desc: "Maecenas feugiat augue ut tincidunt vestibulum. Sed pharetra arcu eget nulla tristique, sed vehicula lorem pharetra.",
        categories: [
            { category: "Art" },
            { category: "Design" },
        ],
        author: {
            createdBy: "Amelia Harris",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-12-19",
        },
        totalComments: 335,
        totalViews: 8300,
        totalLikes: 405,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nullam Non Tortor",
        desc: "Nullam non tortor nec quam aliquam vehicula. Integer vehicula bibendum urna, eu lobortis nulla posuere eu. Donec tempor luctus aliquet.",
        categories: [
            { category: "Education" },
            { category: "Learning" },
        ],
        author: {
            createdBy: "Elijah Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-12-18",
        },
        totalComments: 340,
        totalViews: 8400,
        totalLikes: 410,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Praesent Dignissim Neque Vel",
        desc: "Praesent dignissim neque vel urna bibendum, a vehicula sem molestie. Quisque vel dui sit amet libero sollicitudin egestas in eget.",
        categories: [
            { category: "Science" },
            { category: "Research" },
        ],
        author: {
            createdBy: "Mia Walker",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-12-17",
        },
        totalComments: 345,
        totalViews: 8500,
        totalLikes: 415,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Curabitur Malesuada Elit Eu",
        desc: "Curabitur malesuada elit eu turpis tincidunt, a consequat ex luctus. Donec rhoncus leo nec nunc maximus, et vehicula ligula fermentum.",
        categories: [
            { category: "Books" },
            { category: "Literature" },
        ],
        author: {
            createdBy: "Oliver Phillips",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-12-16",
        },
        totalComments: 350,
        totalViews: 8600,
        totalLikes: 420,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Sed Vulputate Leo Id",
        desc: "Sed vulputate leo id urna suscipit, vel lacinia tortor bibendum. Curabitur feugiat nisi id massa tincidunt ornare.",
        categories: [
            { category: "Gaming" },
            { category: "Entertainment" },
        ],
        author: {
            createdBy: "Sophia Walker",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-12-15",
        },
        totalComments: 355,
        totalViews: 8700,
        totalLikes: 425,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Et Metus Quis",
        desc: "Pellentesque et metus quis magna ultricies venenatis a a augue. Sed tincidunt, risus vel viverra dictum, enim libero semper dui.",
        categories: [
            { category: "Music" },
            { category: "Concerts" },
        ],
        author: {
            createdBy: "Noah Clark",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-12-14",
        },
        totalComments: 360,
        totalViews: 8800,
        totalLikes: 430,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Fringilla Venenatis Eget",
        desc: "Vestibulum fringilla venenatis eget nulla rhoncus. Proin eget dolor tristique, hendrerit mauris sed, lacinia ipsum.",
        categories: [
            { category: "Politics" },
            { category: "Government" },
        ],
        author: {
            createdBy: "Mason Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-12-13",
        },
        totalComments: 365,
        totalViews: 8900,
        totalLikes: 435,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Donec Vitae Mi Auctor",
        desc: "Donec vitae mi auctor, pellentesque quam ut, lacinia ex. Curabitur tincidunt libero sit amet dui ultrices, vitae commodo nisl faucibus.",
        categories: [
            { category: "Nature" },
            { category: "Environment" },
        ],
        author: {
            createdBy: "Ella Walker",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-12-12",
        },
        totalComments: 370,
        totalViews: 9000,
        totalLikes: 440,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Etiam Lobortis Nibh Eget",
        desc: "Etiam lobortis nibh eget massa consectetur, sit amet elementum neque efficitur. Nam id ipsum at purus feugiat fermentum.",
        categories: [
            { category: "Business" },
            { category: "Finance" },
        ],
        author: {
            createdBy: "Sophie Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-12-11",
        },
        totalComments: 375,
        totalViews: 9100,
        totalLikes: 445,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Mauris Non Felis Sit",
        desc: "Mauris non felis sit amet mi interdum condimentum. Vestibulum tincidunt, nunc sit amet volutpat fermentum, velit tortor consectetur risus.",
        categories: [
            { category: "Sports" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "William Clark",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-12-10",
        },
        totalComments: 380,
        totalViews: 9200,
        totalLikes: 450,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Sed Non Nunc Eu",
        desc: "Sed non nunc eu velit blandit facilisis. Nulla eget nibh euismod, scelerisque dolor id, faucibus tellus.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "Emma Walker",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-12-09",
        },
        totalComments: 385,
        totalViews: 9300,
        totalLikes: 455,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Non Nulla Dapibus",
        desc: "Pellentesque non nulla dapibus, varius libero in, rutrum dui. Sed molestie euismod magna, eu condimentum urna fringilla in.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Lucas Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-12-08",
        },
        totalComments: 390,
        totalViews: 9400,
        totalLikes: 460,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Odio Lectus",
        desc: "Vivamus odio lectus, fermentum nec commodo ut, tristique in leo. Ut hendrerit consequat erat, in vehicula enim luctus sit amet.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Sophia Clark",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-12-07",
        },
        totalComments: 395,
        totalViews: 9500,
        totalLikes: 465,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nullam Consectetur Neque At",
        desc: "Nullam consectetur neque at tristique tincidunt. Nulla nec scelerisque metus. Donec at turpis id elit maximus vehicula.",
        categories: [
            { category: "Food" },
            { category: "Cooking" },
        ],
        author: {
            createdBy: "Olivia Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-12-06",
        },
        totalComments: 400,
        totalViews: 9600,
        totalLikes: 470,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Auctor Erat Eu",
        desc: "Vivamus auctor erat eu pulvinar. Praesent accumsan felis at nisi posuere, nec interdum ex interdum. Sed lacinia ligula vel tellus.",
        categories: [
            { category: "Fashion" },
            { category: "Style" },
        ],
        author: {
            createdBy: "Isaac Phillips",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-12-05",
        },
        totalComments: 405,
        totalViews: 9700,
        totalLikes: 475,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Maecenas Eget Semper Ligula",
        desc: "Maecenas eget semper ligula, non maximus eros. Nam auctor, purus eu laoreet ullamcorper, magna lectus interdum orci, nec ornare purus.",
        categories: [
            { category: "Art" },
            { category: "Design" },
        ],
        author: {
            createdBy: "Amelia Walker",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-12-04",
        },
        totalComments: 410,
        totalViews: 9800,
        totalLikes: 480,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nullam Sodales Enim Eu",
        desc: "Nullam sodales enim eu risus tempus, nec molestie metus malesuada. Aliquam ut semper velit, non vestibulum lorem.",
        categories: [
            { category: "Education" },
            { category: "Learning" },
        ],
        author: {
            createdBy: "Elijah Clark",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-12-03",
        },
        totalComments: 415,
        totalViews: 9900,
        totalLikes: 485,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Praesent Ut Neque Eu",
        desc: "Praesent ut neque eu nunc fermentum interdum. Vestibulum feugiat erat at interdum dictum. Donec non tortor vel est convallis commodo.",
        categories: [
            { category: "Science" },
            { category: "Research" },
        ],
        author: {
            createdBy: "Mia Phillips",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-12-02",
        },
        totalComments: 420,
        totalViews: 10000,
        totalLikes: 490,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Curabitur Convallis Neque Eu",
        desc: "Curabitur convallis neque eu ligula tincidunt, eu efficitur dolor feugiat. Ut convallis erat nec justo tincidunt, sed cursus neque convallis.",
        categories: [
            { category: "Books" },
            { category: "Literature" },
        ],
        author: {
            createdBy: "Oliver Phillips",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-12-01",
        },
        totalComments: 425,
        totalViews: 10100,
        totalLikes: 495,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Sed Volutpat Purus In",
        desc: "Sed volutpat purus in nibh scelerisque, in consectetur eros tempor. Proin et augue vel leo laoreet vehicula.",
        categories: [
            { category: "Gaming" },
            { category: "Entertainment" },
        ],
        author: {
            createdBy: "Sophia Walker",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-11-30",
        },
        totalComments: 430,
        totalViews: 10200,
        totalLikes: 500,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Vitae Nunc Et",
        desc: "Pellentesque vitae nunc et augue bibendum congue nec nec orci. Donec in libero vitae nulla efficitur venenatis.",
        categories: [
            { category: "Music" },
            { category: "Concerts" },
        ],
        author: {
            createdBy: "Noah Clark",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-11-29",
        },
        totalComments: 435,
        totalViews: 10300,
        totalLikes: 505,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Non Metus Non",
        desc: "Vestibulum non metus non magna tristique iaculis. Curabitur ac tincidunt quam. Nam vel arcu nec velit ullamcorper mattis.",
        categories

: [
            { category: "Politics" },
            { category: "Government" },
        ],
        author: {
            createdBy: "Mason Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-11-28",
        },
        totalComments: 440,
        totalViews: 10400,
        totalLikes: 510,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Donec Placerat Ex Sit",
        desc: "Donec placerat ex sit amet dui condimentum, at hendrerit lorem feugiat. Morbi efficitur euismod justo sit amet accumsan.",
        categories: [
            { category: "Nature" },
            { category: "Environment" },
        ],
        author: {
            createdBy: "Ella Walker",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-11-27",
        },
        totalComments: 445,
        totalViews: 10500,
        totalLikes: 515,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Consectetur Metus Ut",
        desc: "Vestibulum consectetur metus ut interdum interdum. Integer vel est tristique, egestas eros in, volutpat magna.",
        categories: [
            { category: "Business" },
            { category: "Finance" },
        ],
        author: {
            createdBy: "Sophie Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-11-26",
        },
        totalComments: 450,
        totalViews: 10600,
        totalLikes: 520,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Mauris Mollis Justo Nec",
        desc: "Mauris mollis justo nec ligula eleifend, sed dapibus purus efficitur. Nulla et risus sit amet felis scelerisque pulvinar.",
        categories: [
            { category: "Sports" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "William Clark",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-11-25",
        },
        totalComments: 455,
        totalViews: 10700,
        totalLikes: 525,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Morbi Cursus Dui Non",
        desc: "Morbi cursus dui non dui tristique, eget rhoncus libero efficitur. Curabitur gravida dui ut erat vulputate, sit amet placerat justo pretium.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "Emma Walker",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-11-24",
        },
        totalComments: 460,
        totalViews: 10800,
        totalLikes: 530,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Fusce Euismod Tincidunt Elit",
        desc: "Fusce euismod tincidunt elit, sed scelerisque nulla commodo eu. Sed feugiat lacus a dolor posuere, nec fringilla elit malesuada.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Lucas Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-11-23",
        },
        totalComments: 465,
        totalViews: 10900,
        totalLikes: 535,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Lacinia Augue In",
        desc: "Pellentesque lacinia augue in justo commodo, sed vestibulum velit consequat. Sed aliquet libero eget consectetur auctor.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Sophia Clark",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-11-22",
        },
        totalComments: 470,
        totalViews: 11000,
        totalLikes: 540,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Aliquam Ultricies Dui Eget",
        desc: "Aliquam ultricies dui eget fringilla ullamcorper. Vivamus eget lorem eu felis eleifend vehicula eget eu quam.",
        categories: [
            { category: "Food" },
            { category: "Cooking" },
        ],
        author: {
            createdBy: "Olivia Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-11-21",
        },
        totalComments: 475,
        totalViews: 11100,
        totalLikes: 545,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Cras Eget Tincidunt Turpis",
        desc: "Cras eget tincidunt turpis. Sed eget ante vel elit eleifend pretium ac at est. Vestibulum fermentum consectetur orci, vitae euismod orci.",
        categories: [
            { category: "Fashion" },
            { category: "Style" },
        ],
        author: {
            createdBy: "Isaac Phillips",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-11-20",
        },
        totalComments: 480,
        totalViews: 11200,
        totalLikes: 550,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Maecenas Ornare Enim",
        desc: "Maecenas ornare enim vel lobortis euismod. Curabitur ut purus aliquet, sollicitudin elit at, sollicitudin nisl.",
        categories: [
            { category: "Art" },
            { category: "Design" },
        ],
        author: {
            createdBy: "Amelia Harris",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-11-19",
        },
        totalComments: 485,
        totalViews: 11300,
        totalLikes: 555,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nullam Velit Ligula",
        desc: "Nullam velit ligula, varius et lectus in, interdum hendrerit enim. Curabitur id elit hendrerit, efficitur odio nec, volutpat arcu.",
        categories: [
            { category: "Education" },
            { category: "Learning" },
        ],
        author: {
            createdBy: "Elijah Clark",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-11-18",
        },
        totalComments: 490,
        totalViews: 11400,
        totalLikes: 560,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Praesent Vehicula Felis At",
        desc: "Praesent vehicula felis at nunc fermentum bibendum. Phasellus consectetur, purus vitae pellentesque vestibulum, libero eros semper dui.",
        categories: [
            { category: "Science" },
            { category: "Research" },
        ],
        author: {
            createdBy: "Mia Phillips",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-11-17",
        },
        totalComments: 495,
        totalViews: 11500,
        totalLikes: 565,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Curabitur Eget Mi Id",
        desc: "Curabitur eget mi id ligula tincidunt tincidunt. Fusce ac libero sed nunc ornare feugiat vel a est.",
        categories: [
            { category: "Books" },
            { category: "Literature" },
        ],
        author: {
            createdBy: "Oliver Phillips",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-11-16",
        },
        totalComments: 500,
        totalViews: 11600,
        totalLikes: 570,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Sed Quis Neque Molestie",
        desc: "Sed quis neque molestie, molestie tellus nec, consectetur eros. Integer vel ultrices sem. Nullam sit amet placerat est.",
        categories: [
            { category: "Gaming" },
            { category: "Entertainment" },
        ],
        author: {
            createdBy: "Sophia Walker",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-11-15",
        },
        totalComments: 505,
        totalViews: 11700,
        totalLikes: 575,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Elit Massa",
        desc: "Pellentesque elit massa, euismod eget risus sed, scelerisque interdum magna. Duis et nunc fringilla, dictum mauris at, ultricies ex.",
        categories: [
            { category: "Music" },
            { category: "Concerts" },
        ],
        author: {
            createdBy: "Noah Clark",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-11-14",
        },
        totalComments: 510,
        totalViews: 11800,
        totalLikes: 580,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Sit Amet Nullam",
        desc: "Vestibulum sit amet nulla sit amet lacus varius tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames.",
        categories: [
            { category: "Politics" },
            { category: "Government" },
        ],
        author: {
            createdBy: "Mason Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-11-13",
        },
        totalComments: 515,
        totalViews: 11900,
        totalLikes: 585,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Donec Tincidunt Velit Sed",
        desc: "Donec tincidunt velit sed ex vehicula, ac tincidunt tellus ultricies. Vivamus in velit ac velit fermentum finibus.",
        categories: [
            { category: "Nature" },
            { category: "Environment" },
        ],
        author: {
            createdBy: "Ella Walker",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-11-12",
        },
        totalComments: 520,
        totalViews: 12000,
        totalLikes: 590,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Egestas Justo Eu",
        desc: "Vivamus egestas justo eu tortor faucibus,sed rhoncus justo posuere. Maecenas eget sem eget metus pulvinar vestibulum at sit amet quam.",
        categories: [
            { category: "Business" },
            { category: "Finance" },
        ],
        author: {
            createdBy: "Sophie Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-11-11",
        },
        totalComments: 525,
        totalViews: 12100,
        totalLikes: 595,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Mauris Euismod Orci In",
        desc: "Mauris euismod orci in sem laoreet, sit amet cursus est venenatis. Curabitur a justo vel ligula hendrerit lobortis.",
        categories: [
            { category: "Sports" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "William Clark",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-11-10",
        },
        totalComments: 530,
        totalViews: 12200,
        totalLikes: 600,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Morbi Eget Diam Suscipit",
        desc: "Morbi eget diam suscipit, luctus ex vel, fringilla justo. Proin sollicitudin nisl at ex tempor, id molestie diam accumsan.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "Emma Walker",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-11-09",
        },
        totalComments: 535,
        totalViews: 12300,
        totalLikes: 605,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Fusce Sollicitudin Purus A",
        desc: "Fusce sollicitudin purus a sapien pretium, at auctor urna congue. Vestibulum scelerisque nisl sed fringilla ultricies.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Lucas Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-11-08",
        },
        totalComments: 540,
        totalViews: 12400,
        totalLikes: 610,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Velit Nulla",
        desc: "Pellentesque velit nulla, molestie non hendrerit vel, consectetur nec sem. Integer convallis lacus ac lacus tristique, sit amet sollicitudin justo bibendum.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Sophia Clark",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-11-07",
        },
        totalComments: 545,
        totalViews: 12500,
        totalLikes: 615,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Aliquam Nec Turpis Non",
        desc: "Aliquam nec turpis non purus tempus vestibulum. Maecenas tincidunt nibh id odio dignissim, vel facilisis mi malesuada.",
        categories: [
            { category: "Food" },
            { category: "Cooking" },
        ],
        author: {
            createdBy: "Olivia Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-11-06",
        },
        totalComments: 550,
        totalViews: 12600,
        totalLikes: 620,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Cras Porttitor Dolor Vel",
        desc: "Cras porttitor dolor vel tortor fringilla congue. Ut luctus erat eget velit vehicula fringilla. Suspendisse potenti.",
        categories: [
            { category: "Fashion" },
            { category: "Style" },
        ],
        author: {
            createdBy: "Isaac Phillips",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-11-05",
        },
        totalComments: 555,
        totalViews: 12700,
        totalLikes: 625,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Maecenas Venenatis Sapien Eu",
        desc: "Maecenas venenatis sapien eu urna hendrerit, at egestas nulla tincidunt. Suspendisse potenti. Aliquam in turpis eu leo mattis aliquam.",
        categories: [
            { category: "Art" },
            { category: "Design" },
        ],
        author: {
            createdBy: "Amelia Harris",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-11-04",
        },
        totalComments: 560,
        totalViews: 12800,
        totalLikes: 630,
    },
   

 {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nullam Fermentum Ipsum Eu",
        desc: "Nullam fermentum ipsum eu tortor blandit, a tincidunt augue feugiat. Integer sed velit nec augue ultricies laoreet sit amet vel est.",
        categories: [
            { category: "Education" },
            { category: "Learning" },
        ],
        author: {
            createdBy: "Elijah Clark",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-11-03",
        },
        totalComments: 565,
        totalViews: 12900,
        totalLikes: 635,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Donec Feugiat Lectus In",
        desc: "Donec feugiat lectus in lorem vestibulum, id aliquam dolor imperdiet. In at sapien sit amet dui varius bibendum.",
        categories: [
            { category: "Science" },
            { category: "Research" },
        ],
        author: {
            createdBy: "Mia Phillips",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-11-02",
        },
        totalComments: 570,
        totalViews: 13000,
        totalLikes: 640,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Curabitur Ac Aliquet Leo",
        desc: "Curabitur ac aliquet leo. Ut vitae sapien condimentum, elementum urna at, vehicula lectus. Etiam finibus nisl nec velit dictum, at pellentesque leo efficitur.",
        categories: [
            { category: "Books" },
            { category: "Literature" },
        ],
        author: {
            createdBy: "Oliver Phillips",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-11-01",
        },
        totalComments: 575,
        totalViews: 13100,
        totalLikes: 645,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Sed Euismod Nisl Et",
        desc: "Sed euismod nisl et erat malesuada, vel sodales dui tempus. Integer auctor eros ac justo cursus, id tincidunt ante tincidunt.",
        categories: [
            { category: "Gaming" },
            { category: "Entertainment" },
        ],
        author: {
            createdBy: "Sophia Walker",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-10-31",
        },
        totalComments: 580,
        totalViews: 13200,
        totalLikes: 650,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Cursus Augue At",
        desc: "Pellentesque cursus augue at diam bibendum, ut vestibulum urna ultricies. Curabitur bibendum tincidunt lorem nec posuere.",
        categories: [
            { category: "Music" },
            { category: "Concerts" },
        ],
        author: {
            createdBy: "Noah Clark",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-10-30",
        },
        totalComments: 585,
        totalViews: 13300,
        totalLikes: 655,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Vulputate Nunc Vel",
        desc: "Vestibulum vulputate nunc vel urna dapibus, vel bibendum purus egestas. Cras tincidunt, libero id aliquam aliquam, elit nisi dignissim odio.",
        categories: [
            { category: "Politics" },
            { category: "Government" },
        ],
        author: {
            createdBy: "Mason Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-10-29",
        },
        totalComments: 590,
        totalViews: 13400,
        totalLikes: 660,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Donec Sit Amet Magna",
        desc: "Donec sit amet magna auctor, ultricies lorem a, tincidunt nulla. Proin eu erat eget eros vehicula luctus.",
        categories: [
            { category: "Nature" },
            { category: "Environment" },
        ],
        author: {
            createdBy: "Ella Walker",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-10-28",
        },
        totalComments: 595,
        totalViews: 13500,
        totalLikes: 665,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Ut Dolor Eget",
        desc: "Vivamus ut dolor eget justo tempor faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
        categories: [
            { category: "Business" },
            { category: "Finance"

 },
        ],
        author: {
            createdBy: "Sophie Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-10-27",
        },
        totalComments: 600,
        totalViews: 13600,
        totalLikes: 670,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Mauris Feugiat Neque Sit",
        desc: "Mauris feugiat neque sit amet purus pellentesque, eget varius justo tempus. Fusce tempor est eget placerat faucibus.",
        categories: [
            { category: "Sports" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "William Clark",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-10-26",
        },
        totalComments: 605,
        totalViews: 13700,
        totalLikes: 675,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Morbi Sodales Dolor Eu",
        desc: "Morbi sodales dolor eu nibh lacinia, vel facilisis metus scelerisque. Integer nec mi eget dui elementum dictum.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "Emma Walker",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-10-25",
        },
        totalComments: 610,
        totalViews: 13800,
        totalLikes: 680,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Fusce Mattis Nunc Id",
        desc: "Fusce mattis nunc id neque tempor aliquam. Nullam vel arcu vitae sem suscipit malesuada sit amet a elit.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Lucas Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-10-24",
        },
        totalComments: 615,
        totalViews: 13900,
        totalLikes: 685,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Ut Nulla Placerat",
        desc: "Pellentesque ut nulla placerat, laoreet justo eget, fermentum libero. Sed quis felis in elit iaculis auctor.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Sophia Clark",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-10-23",
        },
        totalComments: 620,
        totalViews: 14000,
        totalLikes: 690,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Aliquam Lobortis Nulla In",
        desc: "Aliquam lobortis nulla in quam vestibulum, quis sagittis tortor hendrerit. Integer id ex ut quam molestie volutpat.",
        categories: [
            { category: "Food" },
            { category: "Cooking" },
        ],
        author: {
            createdBy: "Olivia Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-10-22",
        },
        totalComments: 625,
        totalViews: 14100,
        totalLikes: 695,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Cras Tristique Leo Id",
        desc: "Cras tristique leo id libero volutpat, ut rutrum odio dapibus. Sed eget erat id tortor feugiat accumsan.",
        categories: [
            { category: "Fashion" },
            { category: "Style" },
        ],
        author: {
            createdBy: "Isaac Phillips",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-10-21",
        },
        totalComments: 630,
        totalViews: 14200,
        totalLikes: 700,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Maecenas Eu Tellus Nec",
        desc: "Maecenas eu tellus nec ex tincidunt mattis in id felis. Duis tincidunt eros eget tempor facilisis.",
        categories: [
            { category: "Art" },
            { category: "Design" },
        ],
        author: {
            createdBy: "Amelia Harris",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-10-20",
        },
        totalComments: 635,
        totalViews: 14300,
        totalLikes: 705,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Nulla Eget Sapien Sit",
        desc: "Nulla eget sapien sit amet felis sagittis congue vel nec arcu. Ut vitae urna vel dui mattis sodales.",
        categories: [
            { category: "Education" },
            { category: "Learning" },
        ],
        author: {
            createdBy: "Elijah Clark",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-10-19",
        },
        totalComments: 640,
        totalViews: 14400,
        totalLikes: 710,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Praesent Euismod Eros Sed",
        desc: "Praesent euismod eros sed consectetur interdum. In nec metus at nulla facilisis fermentum.",
        categories: [
            { category: "Science" },
            { category: "Research" },
        ],
        author: {
            createdBy: "Mia Phillips",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-10-18",
        },
        totalComments: 645,
        totalViews: 14500,
        totalLikes: 715,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Curabitur A Facilisis Nisl",
        desc: "Curabitur a facilisis nisl. Curabitur varius est et urna egestas, ac sodales ligula rhoncus.",
        categories: [
            { category: "Books" },
            { category: "Literature" },
        ],
        author: {
            createdBy: "Oliver Phillips",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-10-17",
        },
        totalComments: 650,
        totalViews: 14600,
       

 totalLikes: 720,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Sed Venenatis Odio In",
        desc: "Sed venenatis odio in convallis faucibus. Suspendisse id velit dictum, condimentum urna quis, maximus mauris.",
        categories: [
            { category: "Gaming" },
            { category: "Entertainment" },
        ],
        author: {
            createdBy: "Sophia Walker",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-10-16",
        },
        totalComments: 655,
        totalViews: 14700,
        totalLikes: 725,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque Orci Luctus",
        desc: "Pellentesque orci luctus, euismod odio a, vehicula arcu. Phasellus eu dolor at nunc blandit congue ac id lacus.",
        categories: [
            { category: "Music" },
            { category: "Concerts" },
        ],
        author: {
            createdBy: "Noah Clark",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-10-15",
        },
        totalComments: 660,
        totalViews: 14800,
        totalLikes: 730,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vestibulum Euismod Magna Nec",
        desc: "Vestibulum euismod magna nec lacinia luctus. Nullam consectetur erat vel nisi fermentum, sed vestibulum dolor mattis.",
        categories: [
            { category: "Politics" },
            { category: "Government" },
        ],
        author: {
            createdBy: "Mason Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-10-14",
        },
        totalComments: 665,
        totalViews: 14900,
        totalLikes: 735,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Donec Sit Amet Euismod",
        desc: "Donec sit amet euismod urna. Ut nec sapien et lectus cursus bibendum. Curabitur vitae leo in ligula facilisis venenatis.",
        categories: [
            { category: "Nature" },
            { category: "Environment" },
        ],
        author: {
            createdBy: "Ella Walker",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-10-13",
        },
        totalComments: 670,
        totalViews: 15000,
        totalLikes: 740,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Vivamus Pharetra Dolor In",
        desc: "Vivamus pharetra dolor in tincidunt egestas. Nullam eu justo nec sem scelerisque lacinia at sit amet lorem.",
        categories: [
            { category: "Business" },
            { category: "Finance" },
        ],
        author: {
            createdBy: "Sophie Turner",
            photoProfile: "/img/blog/profile-4.jpg",
            createdAt: "2023-10-12",
        },
        totalComments: 675,
        totalViews: 15100,
        totalLikes: 745,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Mauris Vel Diam Dapibus",
        desc: "Mauris vel diam dapibus, pretium lorem vel, laoreet orci. Ut vehicula mi quis est efficitur, sed fringilla libero pretium.",
        categories: [
            { category: "Sports" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "William Clark",
            photoProfile: "/img/blog/profile-5.jpg",
            createdAt: "2023-10-11",
        },
        totalComments: 680,
        totalViews: 15200,
        totalLikes: 750,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Morbi Vitae Felis Eget",
        desc: "Morbi vitae felis eget lectus tincidunt auctor sit amet et elit. Sed auctor dolor vel enim fringilla, a porttitor libero tempor.",
        categories: [
            { category: "Technology" },
            { category: "Web Development" },
        ],
        author: {
            createdBy: "Emma Walker",
            photoProfile: "/img/blog/profile-1.jpg",
            createdAt: "2023-10-10",
        },
        totalComments: 685,
        totalViews: 15300,
        totalLikes: 755,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Fusce Eget Molestie Neque",
        desc: "Fusce eget molestie neque, sit amet suscipit ex. Phasellus quis augue nec arcu luctus ultricies sit amet vitae purus.",
        categories: [
            { category: "Health" },
            { category: "Fitness" },
        ],
        author: {
            createdBy: "Lucas Phillips",
            photoProfile: "/img/blog/profile-2.jpg",
            createdAt: "2023-10-09",
        },
        totalComments: 690,
        totalViews: 15400,
        totalLikes: 760,
    },
    {
        cover: "https://source.unsplash.com/random/800x600",
        title: "Pellentesque At Lacus Enim",
        desc: "Pellentesque at lacus enim. Duis in odio aliquet, ultricies neque in, maximus ligula. Duis tempus, ex id pulvinar efficitur.",
        categories: [
            { category: "Travel" },
            { category: "Adventure" },
        ],
        author: {
            createdBy: "Sophia Clark",
            photoProfile: "/img/blog/profile-3.jpg",
            createdAt: "2023-10-08",
        },
        totalComments: 695,
        totalViews: 15500,
        totalLikes: 765,
    },
]