import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';
import React, { Suspense } from 'react'

const BasicAccordionCard = React.lazy(() => import('@/components/accordion/basic/card'));
const BoxAccordionCard = React.lazy(() => import('@/components/accordion/boxed/card'));

export const metadata: Metadata = {
    title: "Accordion",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Accordion"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <BasicAccordionCard></BasicAccordionCard>
                    </Suspense>
                </div>

                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <BoxAccordionCard></BoxAccordionCard>
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default page