import { Grid } from '@/components/grid';
import CardBasicProgress from '@/components/progress-bar/basic/card';
import CardLabelProgress from '@/components/progress-bar/label/card';
import CardBlankSlide from '@/components/slide-over/blank/card';
import CardCloseSlide from '@/components/slide-over/close/card';
import Title from '@/components/title/title';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Slide Over",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Slide Over"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <CardBlankSlide></CardBlankSlide>
                </div>

                <div className='flex flex-col gap-5'>
                    <CardCloseSlide></CardCloseSlide>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
