import React, { Suspense } from 'react';
import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';

const CardBlankSlide = React.lazy(() => import('@/components/slide-over/blank/card'));
const CardCloseSlide = React.lazy(() => import('@/components/slide-over/close/card'));

export const metadata: Metadata = {
    title: "Slide Over",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Slide Over"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardBlankSlide></CardBlankSlide>
                    </Suspense>
                </div>

                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardCloseSlide></CardCloseSlide>
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
