import React, { Suspense } from 'react';
import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';

const CardFormCheckbox = React.lazy(() => import('@/forms/checkbox/card'));
const CardFormGroup = React.lazy(() => import('@/forms/group/card'));
const CardFormHorizontal = React.lazy(() => import('@/forms/horizontal/card'));
const CardFormRadio = React.lazy(() => import('@/forms/radio/card'));
const CardFormRegular = React.lazy(() => import('@/forms/regular-form/card'));
const CardFormSelect = React.lazy(() => import('@/forms/select/card'));
const CardFormVertical = React.lazy(() => import('@/forms/vertical/card'));

export const metadata: Metadata = {
    title: "Regular Form",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Regular Form"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardFormRegular></CardFormRegular>
                    </Suspense>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardFormGroup></CardFormGroup>
                    </Suspense>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardFormCheckbox></CardFormCheckbox>
                    </Suspense>
                </div>

                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardFormVertical></CardFormVertical>
                    </Suspense>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardFormHorizontal></CardFormHorizontal>
                    </Suspense>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardFormRadio></CardFormRadio>
                    </Suspense>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardFormSelect></CardFormSelect>
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
