import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import CardFormCheckbox from '@/forms/checkbox/card';
import CardFormGroup from '@/forms/group/card';
import CardFormHorizontal from '@/forms/horizontal/card';
import CardFormRadio from '@/forms/radio/card';
import CardFormRegular from '@/forms/regular-form/card';
import CardFormVertical from '@/forms/vertical/card';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Regular Form",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Regular Form"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <CardFormRegular></CardFormRegular>
                    <CardFormGroup></CardFormGroup>
                    <CardFormCheckbox></CardFormCheckbox>
                </div>

                <div className='flex flex-col gap-5'>
                    <CardFormVertical></CardFormVertical>
                    <CardFormHorizontal></CardFormHorizontal>
                    <CardFormRadio></CardFormRadio>
                </div>
            </Grid>
        </main>
    );
}

export default page