import React from 'react'
import type {Metadata}
from "next";

export const metadata: Metadata = {
    title: "Dashboard", 
    description: "Generated by create next app"
};

const Home = () => {
  return (
    <main>
      homepage
    </main>
  )
}

export default Home