import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "post",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <main>
            post
        </main>
    );
}

export default page