import React, { Suspense } from 'react';
import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';

const CardBlankModal = React.lazy(() => import('@/components/modal/blank/card'));
const CardDeleteModal = React.lazy(() => import('@/components/modal/delete/card'));
const CardSuccessModal = React.lazy(() => import('@/components/modal/success/card'));
const CardWarningModal = React.lazy(() => import('@/components/modal/warning/card'));

export const metadata: Metadata = {
    title: "Modal",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Modal"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardBlankModal></CardBlankModal>
                        <CardWarningModal></CardWarningModal>
                    </Suspense>
                </div>

                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardDeleteModal></CardDeleteModal>
                        <CardSuccessModal></CardSuccessModal>
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
