import CardBlankModal from '@/components/modal/blank/card';
import CardDeleteModal from '@/components/modal/delete/card';
import CardSuccessModal from '@/components/modal/success/card';
import CardWarningModal from '@/components/modal/warning/card';
import Title from '@/components/title/title';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Modal",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Modal"></Title>

            <div className="grid grid-cols-2 gap-5">
                <div className='flex flex-col gap-5'>
                    <CardBlankModal></CardBlankModal>
                    <CardWarningModal></CardWarningModal>
                </div>

                <div className='flex flex-col gap-5'>
                    <CardDeleteModal></CardDeleteModal>
                    <CardSuccessModal></CardSuccessModal>
                </div>
            </div>
        </main>
    );
}

export default Page;
