import React, { Suspense } from 'react';
import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Chart",
    description: "Generated by create next app"
};

const CardChartDonut = React.lazy(() => import('@/widgets/charts/donut/card'));
const CardChartHorizontal = React.lazy(() => import('@/widgets/charts/horizontal/card'));
const CardChartLine = React.lazy(() => import('@/widgets/charts/line/card'));
const CardChartPie = React.lazy(() => import('@/widgets/charts/pie/card'));
const LazyCardChartStacked = React.lazy(() => import('@/widgets/charts/stacked/card'));
const CardChartVertical = React.lazy(() => import('@/widgets/charts/vertical/card'));

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Chart"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardChartVertical />
                    </Suspense>

                    <Suspense fallback={<div>Loading...</div>}>
                        <CardChartHorizontal />
                    </Suspense>

                    <Suspense fallback={<div>Loading...</div>}>
                        <CardChartDonut />
                    </Suspense>
                </div>

                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <LazyCardChartStacked />
                    </Suspense>

                    <Suspense fallback={<div>Loading...</div>}>
                        <CardChartLine />
                    </Suspense>

                    <Suspense fallback={<div>Loading...</div>}>
                        <CardChartPie />
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
