import BasicBtnCard from '@/components/card/button/basic-button-card';
import LinkBtnCard from '@/components/card/button/link-button-card';
import OutlineBtnCard from '@/components/card/button/outline-button-card';
import RoundedBtnCard from '@/components/card/button/rounded-button-card';
import SizeBtnCard from '@/components/card/button/sizes-button-card';
import Title from '@/components/title';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Regular button",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="buttons"></Title>

            <div className="grid grid-cols-2 gap-5">
                <div className='flex flex-col gap-5'>
                    <BasicBtnCard></BasicBtnCard>
                    <SizeBtnCard></SizeBtnCard>
                    <LinkBtnCard></LinkBtnCard>
                </div>

                <div className='flex flex-col gap-5'>
                    <OutlineBtnCard></OutlineBtnCard>
                    <RoundedBtnCard></RoundedBtnCard>
                </div>
            </div>
        </main>
    );
}

export default Page;
