import Card from '@/components/card';
import { CodeBasicBtn } from '@/components/show code/code-basic-button';
import Title from '@/components/title';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Regular button",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="buttons"></Title>

            <div className="grid grid-cols-2 gap-5">
                {/* Basic Button */}
                <Card 
                    title="Example Card">
                    <div className="p-5">
                        <CodeBasicBtn isChecked />
                    </div>
                </Card>
            </div>
        </main>
    );
}

export default Page;
