import React, { Suspense } from 'react';
import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';

const CardFileUploadMultiple = React.lazy(() => import('@/forms/file-upload/multiple/card'));
const CardFileUpload = React.lazy(() => import('@/forms/file-upload/single/card'));

export const metadata: Metadata = {
    title: "Dropzone",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Dropzone"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardFileUpload></CardFileUpload>
                    </Suspense>
                </div>

                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardFileUploadMultiple></CardFileUploadMultiple>
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
