import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import CardFileUploadMultiple from '@/forms/file-upload/multiple/card';
import CardFileUpload from '@/forms/file-upload/single/card';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Dropzone",
    description: "Generated by create next app"
};

const page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Dropzone"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <CardFileUpload></CardFileUpload>
                </div>

                <div className='flex flex-col gap-5'>
                    <CardFileUploadMultiple></CardFileUploadMultiple>
                </div>
            </Grid>
        </main>
    );
}

export default page