import { Grid } from '@/components/grid';
import CardBasicTab from '@/components/tab/basic/card';
import Title from '@/components/title/title';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Tab",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Tab"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <CardBasicTab></CardBasicTab>
                </div>

                <div className='flex flex-col gap-5'>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
