import React, { Suspense } from 'react';
import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';

const CardBasicProgress = React.lazy(() => import('@/components/progress-bar/basic/card'));
const CardLabelProgress = React.lazy(() => import('@/components/progress-bar/label/card'));

export const metadata: Metadata = {
    title: "Progressbar",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="Progressbar"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardBasicProgress></CardBasicProgress>
                    </Suspense>
                </div>

                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardLabelProgress></CardLabelProgress>
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
