import React, { Suspense } from 'react';
import { Grid } from '@/components/grid';
import Title from '@/components/title/title';
import { Metadata } from 'next';

const CardBasicDropdown = React.lazy(() => import('@/components/dropdown/basic/card'));
const CardHeadFootDropdown = React.lazy(() => import('@/components/dropdown/header-footer/card'));
const CardHeadIconDropdown = React.lazy(() => import('@/components/dropdown/header-icon/card'));
const CardIconDropdown = React.lazy(() => import('@/components/dropdown/icon/card'));
const CardScrollDropdown = React.lazy(() => import('@/components/dropdown/scroll/card'));

export const metadata: Metadata = {
    title: "Dropdown",
    description: "Generated by create next app"
};

const Page = () => {
    return (
        <main className='flex flex-col gap-5'>
            <Title name="dropdown"></Title>

            <Grid>
                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardBasicDropdown></CardBasicDropdown>
                        <CardHeadFootDropdown></CardHeadFootDropdown>
                        <CardIconDropdown></CardIconDropdown>
                    </Suspense>
                </div>

                <div className='flex flex-col gap-5'>
                    <Suspense fallback={<div>Loading...</div>}>
                        <CardScrollDropdown></CardScrollDropdown>
                        <CardHeadIconDropdown></CardHeadIconDropdown>
                    </Suspense>
                </div>
            </Grid>
        </main>
    );
}

export default Page;
